# paths to config files
reads: "/scratch/indikar_root/indikar1/shared_data/pipeline_test/inputs/barcode01/"
reference: "/nfs/turbo/umms-indikar/shared/genomes/GRCh38_mm2_indexed/GCA_000001405.15_GRCh38_genomic.fna"
assembly: "/nfs/turbo/umms-indikar/shared/genomes/GRCh38_assmebly/assembly.csv"
output: "/scratch/indikar_root/indikar1/shared_data/pipeline_test/barcode01_mm2_results/"
aligner: "minimap2 -ax map-ont"
threads: 36
chromosome: 19
assembly_field: "GenBank"
