# paths to config files
reads: "/nfs/turbo/umms-indikar/shared/projects/poreC/pipeline_test/inputs/reads/"
reference: "/nfs/turbo/umms-indikar/shared/projects/poreC/pipeline_test/inputs/mm2_reference/GCF_000001635.27_GRCm39_genomic.fna"
assembly: "/nfs/turbo/umms-indikar/shared/projects/poreC/pipeline_test/inputs/assembly/GRCm39_Assembly.csv"
output: "/nfs/turbo/umms-indikar/shared/projects/poreC/pipeline_test/outputs/"
threads: 36
chromosome: 19
