# paths to config files
reads: "/nfs/turbo/umms-indikar/shared/projects/IR_SingleCell/fastq_pass/barcode06/"
reference: "/nfs/turbo/umms-indikar/shared/genomes/GRCh38_mm2_indexed/GCA_000001405.15_GRCh38_genomic.fna"
assembly: "assembly_files/GRCh38_assmebly.csv"
output: "/scratch/indikar_root/indikar1/shared_data/pipeline_test/barcode06_mm2_results/"
aligner: "minimap2 -ax map-ont"
threads: 36
assembly_field: "GenBank"
fastq_filetype: ".gz"
